# Generated by Django 6.0 on 2026-01-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conquista',
            options={},
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='conquista',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conquista',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
